[phases.setup]
nixPkgs = ["python311", "git", "python311Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r api/requirements.txt"]

[start]
cmd = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
